### ISSUE TITLE
 No tests executed. - Control V-2236

### ISSUE THREAD

**Issue by superyarick** [mitre/nginx-baseline#4]
Command line
```sh
inspec exec  nginx-baseline/controls/V-2236.rb -i ~/.ssh/id_rsa -t ssh://root@ubuntu.host:2211  --log-level=debug
```
Error: No tests executed.

**Comment by superyarick** [comment]
Target system is running Ububuntu.  The interesting part is that other controls ( RHEL Specific ) execute just fine or get skipped

**Comment by rx294** [comment]
Thank you for the note. I will update the control to work on debian systems as well.
